// https://discourse.threejs.org/t/r2f-and-rapier-physics-to-build-floating-bubbles/64120

import { createRoot } from 'react-dom/client'
import './styles.css'
import { App } from './App'
import Test from './Test'
import NewVersion from './NewVersion'
import TeamSection from './Team'
import FloatingImagesV5 from './Team/FloatingImagesv5'

createRoot(document.getElementById('root')).render(
  <div style={{ background: "#010313", height: "100vh" }}>
    {/* <App
      data={[
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
        { color: '#444', image: '/team-members/Abu_Sufian.jpg', scale: 1.5, text: 'from' },
        { color: '#444', image: '/team-members/Abul_Hashem_Mohon.webp', scale: 1, text: 'the' },
        { color: '#ff4060', image: '/team-members/alamin_bro.jpg', scale: 1.4, text: 'journey' },
        { color: '#444', image: '/team-members/anwar.jpg', scale: 1.5, text: 'of' },
        { color: '#444', image: '/team-members/Awlad_Hossain.webp', scale: 1, text: 'the' },
        { color: '#ffdf10', image: '/team-members/Fardin_Amin_Arpon.jpg', scale: 1.4, text: 'sun' },
        { color: '#444', image: '/team-members/israfil.jpg', scale: 1.4, text: 'through' },
        { color: '#444', image: '/team-members/Mridul-Das.png', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Muktadir-tamim.webp', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/rasel.jpg', scale: 1, text: 'signs' },
        { color: '#444', image: '/team-members/jhankar-mahbub.jpg', scale: 1.25, text: 'come' },
        { color: '#444', image: '/team-members/Saiful_Islam_Sojib.jpg', scale: 1.4, text: 'the' },
        { color: '#ff4060', image: '/team-members/Md.-Zahid-Hossain.jpg', scale: 1.25, text: 'legend' },
        { color: '#444', image: '/team-members/MD Sakib Ahmed.jpg', scale: 1.4, text: 'of' },
        { color: '#444', image: '/team-members/Emdadul_Hoque_Tareque.jpg', scale: 1.5, text: 'the' },
        { color: '#ff4060', image: '/team-members/Azizul_Islam_Milton.jpg', scale: 1.4, text: 'twelve' },
        { color: '#ff4060', image: '/team-members/Md._Mehedi_Hasan.png', scale: 1.25, text: 'labours' },
        { color: '#444', image: '/team-members/Md-Abdullah-All-Naim.jpeg', scale: 1, text: 'of' },
        { color: '#ff4060', image: '/team-members/Farhan-Elias.jpeg', scale: 1.25, text: 'hercules' },
      ]}
    /> */}
    {/* <TeamSection /> */}
    <FloatingImagesV5 />

  </div>,
)
